### ISSUE TITLE
java.lang.NoSuchMethodError: me.jellysquid.mods.sodium.client.gui.options.control.CyclingControl

### ISSUE THREAD

**Issue by AntonSax** [Asek3/Rubidium#654]
Crash using Pixelmon Modpack + Rubidium, Rubidium Extras, and Oculus

GPU: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 537.42, NVIDIA Corporation

[crash-2023-10-18_23.04.30-client.txt](https://github.com/Asek3/Rubidium/files/13038162/crash-2023-10-18_23.04.30-client.txt)

**Comment by amaury-d** [comment]
I could isolate the issue on Rubidium 0.2.13. The menu is still working on 0.2.12.

Disabling Magnesium/Rubidium Extras and Embeddium/Rubidium Dynamic Lights didn't solve the issue.
Tested on MC 1.16.5

**Comment by nickkeane** [comment]
Try replacing the Rubidium mods with Embeddium mods (Embeddium, Embeddium/Rubidium Extras AKA Magnesium Extras). Or see if an older version of Oculus works.

It's likely Oculus is referencing a newer Sodium function the older Rubidium builds don't provide.

Edit: Tested with FTB Academy 1.16.5, Seems to be working:
[x] Embeddium
[x] Oculus
[ ] Rubiddium
[x] Magnesium Extras
[x] Lightspeed

Complementary Unbound 5.2.1 - Bloom Off (For better Holo sign display)
